### ISSUE TITLE
Reverse proxy must ignore object argument

### ISSUE THREAD

**Issue by elky** [redsolution/django-menu-proxy#1]

**Comment by a-iv** [comment]
Понимаю вопрос очень своевременный, но всё же:
что-что?

**Comment by elky** [comment]
![1](https://cloud.githubusercontent.com/assets/209663/5912374/18e3616c-a5f5-11e4-88f8-9d1ef7355338.jpg)
Не помню :)

**Comment by summerisgone** [comment]
A?
